apiVersion: batch/v1
kind: Job
metadata:
    name: qwen3-real-235b-fp8-table-extraction-final-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: qwen3-real-235b-table-extraction-vllm-batched-job
    spec:
      priorityClassName: unimportant
      containers:
      - name: qwen3-real-235b-table-extraction-vllm-batched-job
        image: registry.datexis.com/s92818/remote-work-vllm-latest-working
        command: ["/bin/sh", "-c"]
        args: [
          "python3 -u /pvc/thesis_benchmarks/final_real_table_extraction_benchmark_vllm.py --model_name Qwen/Qwen3-235B-A22B-Instruct-2507-FP8 --no_think --n_loops 1 --batched --tensor_parallel_size 4"
        ]
        resources:
          requests:
              cpu: "2"
              memory: "32Gi"
              nvidia.com/gpu: "4"
          limits:
            nvidia.com/gpu: "4"
            memory: 128Gi
            cpu: "32"
        env:
          - name: LANG
            value: 'C.UTF-8'
          - name: HF_HOME
            value: "/pvc/hub_cache"
          - name: OMP_NUM_THREADS
            value: "1"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
        volumeMounts:
          - name: vllm-pvc
            mountPath: /pvc
          - name: dshm
            mountPath: /dev/shm
      nodeSelector:
        # kubernetes.io/hostname: cl-worker29
        gpu: h200
      imagePullSecrets:
        - name: private-registry-auth
      volumes:
        - name: vllm-pvc
          persistentVolumeClaim:
            claimName: vllm-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      restartPolicy: Never