apiVersion: batch/v1
kind: Job
metadata:
    name: qwen-32b-binary-job-1x-b200
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: qwen-32b-binary-job-1x-b200
    spec:
      containers:
      - name: qwen-32b-binary-job-1x-b200
        image: registry.datexis.com/s92818/remote-work-vllm:latest
        command: ["/bin/sh", "-c"]
        args: [
          "python3 -u /pvc/thesis_benchmarks/final_page_identification_benchmark_vllm_gpu_comparison.py --classifier binary --batched --model_name Qwen/Qwen2.5-32B-Instruct --test_run --n_loops 2 --tensor_parallel_size 1 --gpu b200"
        ]
        resources:
          requests:
              cpu: "2"
              memory: "32Gi"
              nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
            memory: 128Gi
            cpu: "32"
        env:
          - name: LANG
            value: 'C.UTF-8'
          - name: HF_HOME
            value: "/pvc/hub_cache"
          - name: OMP_NUM_THREADS
            value: "1"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
        volumeMounts:
          - name: vllm-pvc
            mountPath: /pvc
          - name: dshm
            mountPath: /dev/shm
      nodeSelector:
        # kubernetes.io/hostname: cl-worker29
        gpu: b200
      imagePullSecrets:
        - name: private-registry-auth
      volumes:
        - name: vllm-pvc
          persistentVolumeClaim:
            claimName: vllm-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      restartPolicy: Never