apiVersion: batch/v1
kind: Job
metadata:
    name: phi4-15b--real-table-extraction-final-job2
    # namespace: s92818
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: phi4-15b--real-table-extraction-final-job
    spec:
      containers:
      - name: phi4-15b--real-table-extraction-final-job
        image: registry.datexis.com/s92818/remote-work-vllm:latest
        command: ["/bin/sh", "-c"]
        args: [
          "python3 -u /pvc/thesis_benchmarks/final_real_table_extraction_extended_benchmark_vllm.py --model_name microsoft/phi-4 --n_loops 1 --batched"
        ]
        resources:
          requests:
              cpu: "4"
              memory: "32Gi"
              nvidia.com/gpu: "4"
          limits:
            nvidia.com/gpu: "4"
            memory: 128Gi
            cpu: "32"
        env:
          - name: LANG
            value: 'C.UTF-8'
          - name: HF_HOME
            value: "/pvc/hub_cache"
          - name: OMP_NUM_THREADS
            value: "1"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
        volumeMounts:
          - name: vllm-pvc
            mountPath: /pvc
      nodeSelector:
        # kubernetes.io/hostname: cl-worker29
        gpu: a100
      imagePullSecrets:
        - name: private-registry-auth
      volumes:
        - name: vllm-pvc
          persistentVolumeClaim:
            claimName: vllm-pvc
      restartPolicy: Never