apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstpod
  labels:
    app: firstpod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: firstpod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: firstpod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
