apiVersion: batch/v1
kind: Job
metadata:
    name: mistral-2410-8b-synth-table-extraction-from-md-final-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: mistral-2410-8b-synth-table-extraction-from-pdf-final-job
    spec:
      priorityClassName: unimportant
      containers:
      - name: mistral-2410-8b-synth-table-extraction-from-pdf-final-job
        image: registry.datexis.com/s92818/remote-work-vllm-0-10-0:latest
        command: ["/bin/sh", "-c"]
        args: [
          "python3 -u /pvc/thesis_benchmarks/final_synth_table_extraction_from_md_benchmark_vllm.py --model_name mistralai/Ministral-8B-Instruct-2410 --combine_system_prompts --n_loops 1 --batched --tensor_parallel_size 2"
        ]
        resources:
          requests:
              cpu: "2"
              memory: "32Gi"
              nvidia.com/gpu: "2"
          limits:
            nvidia.com/gpu: "2"
            memory: 128Gi
            cpu: "32"
        env:
          - name: LANG
            value: 'C.UTF-8'
          - name: HF_HOME
            value: "/pvc/hub_cache"
          - name: OMP_NUM_THREADS
            value: "1"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
        volumeMounts:
          - name: vllm-pvc
            mountPath: /pvc
          - name: dshm
            mountPath: /dev/shm
      nodeSelector:
        # kubernetes.io/hostname: cl-worker29
        gpu: a100
      imagePullSecrets:
        - name: private-registry-auth
      volumes:
        - name: vllm-pvc
          persistentVolumeClaim:
            claimName: vllm-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
      restartPolicy: Never