apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-work-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-work-vllm
  template:
    metadata:
      labels:
        app: remote-work-vllm
    spec:
      containers:
      - name: remote-work-vllm
        image: registry.datexis.com/s92818/remote-work-vllm-gpt-oss
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: vllm-pvc
          mountPath: /pvc
        - name: ssh-key
          mountPath: /root/ssh-key
        - name: dshm
          mountPath: /dev/shm
        ports:
        # - containerPort: 8000  # vLLM exposes the API on port 8000
        - containerPort: 22
        # command: ["/bin/sh", "-c"]
        # args: [
        #   "vllm serve Qwen/Qwen2.5-7B --port 8000 --host 0.0.0.0 --tensor-parallel-size 1"
        # ]
        lifecycle:
          postStart:
            exec:
              command: [
                "/bin/sh", "-c", 
                "cat /root/ssh-key/id_ed25519.pub >> /root/.ssh/authorized_keys && \
                echo \"export LANG='$LANG'\" >> /root/.profile && \
                echo \"export HF_HOME='$HF_HOME'\" >> /root/.profile && \
                echo \"export OMP_NUM_THREADS='$OMP_NUM_THREADS'\" >> /root/.profile && \
                if [ -n \"$HUGGING_FACE_HUB_TOKEN\" ]; then echo \"export HUGGING_FACE_HUB_TOKEN='$HUGGING_FACE_HUB_TOKEN'\" >> /root/.profile; fi"
                ]
        resources:
          requests:
              cpu: "2"
              memory: "32Gi"
              nvidia.com/gpu: "2"
          limits:
            nvidia.com/gpu: "2"
            memory: 128Gi
            cpu: "32"
        env:
          - name: LANG
            value: 'C.UTF-8'
          - name: HF_HOME
            value: "/pvc/hub_cache"
          - name: OMP_NUM_THREADS
            value: "1"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
      nodeSelector:
        gpu: a100
      imagePullSecrets:
      - name: private-registry-auth
      volumes:
        - name: vllm-pvc
          persistentVolumeClaim:
            claimName: vllm-pvc
        - name: ssh-key
          secret:
            secretName: my-ssh-public-key
            defaultMode: 256
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi