apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-pvc
  labels:
    app: vllm-deployment
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6000Gi
  storageClassName: shared
