apiVersion: batch/v1
kind: Job
metadata:
    name: gemma3n-8b-job-final
    # namespace: s92818
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gemma3-4b-job
    spec:
      priorityClassName: unimportant
      containers:
      - name: gemma3-4b-job
        image: registry.datexis.com/s92818/remote-work-vllm:latest
        command: ["/bin/sh", "-c"]
        args: [
          "python3 -u /pvc/thesis_benchmarks/page_detection_benchmark_llm.py --model_name google/gemma-3n-E4B-it --n_loops 1 --combine_system_prompts --verbose --classifier five_classes"
        ]
        resources:
          requests:
              cpu: "4"
              memory: "32Gi"
              nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
            memory: 128Gi
            cpu: "32"
        env:
          - name: LANG
            value: 'C.UTF-8'
          - name: HF_HOME
            value: "/pvc/hub_cache"
          - name: OMP_NUM_THREADS
            value: "1"
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: token
        volumeMounts:
          - name: vllm-pvc
            mountPath: /pvc
      nodeSelector:
        # kubernetes.io/hostname: cl-worker29
        gpu: h200
      imagePullSecrets:
        - name: private-registry-auth
      volumes:
        - name: vllm-pvc
          persistentVolumeClaim:
            claimName: vllm-pvc
      restartPolicy: Never