---
title: "Extraction of tabular data from annual reports with LLMs"
author: "Simon Sch채fer"
date: "September 1, 2025"
site: "bookdown::bookdown_site"
output:
  # bookdown::pdf_book:
  bookdown::pdf_document2:
    toc: false
    includes:
      in_header:
        - bhtThesis.sty
        - preamble.tex
  bookdown::gitbook: default
css: "style.css"
documentclass: book
bibliography: ["DS 4th: Extracting financial data from annual reports.bib"]
biblio-style: apa
link-citations: yes
csl: apa-single-spaced.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\pagenumbering{gobble}
\pagestyle{empty}

# {.unlisted .unnumbered}

## Abstract {.unlisted .unnumbered}

Content of this thesis is a benchmark on information extraction from PDFs. The focus are annual reports of German companies. Special characteristic of the task is handling hierarchies in tables with financial data to prepare the data for import into a relational database.

The benchmark is composed of three sub tasks and the performance of different open source large language models is tested with different prompting approaches and compared to alternative methods.

## Zusammenfassung {.unlisted .unnumbered}

Gegenstand dieser Arbeit ist ein Benchmark zur Informationsextraktion aus PDF-Dateien. Dabei wird sich auf das Auslesen der Bilanzen und Gewinn- und Verlustrechnungen aus Jahresabschl체ssen deutscher Unternehmen beschr채nkt. Ein besonderer Aspekt der Aufgabe ist die Ber체cksichtigung der Hierarchie innerhalb der Tabellen, um die Werte einem festen Schema zuzuordnen und so den Import in eine relationale Datenbank vorzubereiten.

## Notes {.unlisted .unnumbered}

* Qwen 2.5 hat zweiseitige GuV von IBB entdeckt und zur Anpassung der Ground Truth

\pagestyle{fancy}

\cleardoublepage
\pagenumbering{roman}
\setcounter{page}{1}
\tableofcontents

\cleardoublepage
\pagenumbering{arabic}
\setcounter{page}{1}